In [1]:
#importing essential libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from matplotlib import rcParams as rcP
%matplotlib inline

In [3]:
df = pd.read_csv(r'C:\Users\inter\Desktop\Mansi\Pune house\Pune_rent.csv')
df.head()

,seller_type,bedroom,layout_type,property_type,locality,price,area,furnish_type,bathroom
0,OWNER,1,BHK,Independent Floor,Mundhwa,"6,750",450,Unfurnished,1
1,OWNER,2,BHK,Apartment,Wakad,"18,000",916,Unfurnished,2
2,OWNER,3,BHK,Apartment,Wagholi,"16,500",1085,Semi-Furnished,3
3,OWNER,1,RK,Studio Apartment,Kothrud,"8,000",250,Furnished,1
4,OWNER,2,BHK,Apartment,Yerawada,"25,000",1005,Semi-Furnished,2

In [4]:
df.shape

(22800, 9)

In [5]:
df.describe().transpose()

           count         mean         std    min    25%    50%     75%     max
bedroom  22800.0     1.873465    0.793189    1.0    1.0    2.0     2.0     8.0
area     22800.0  1041.622588  588.915990  100.0  650.0  960.0  1200.0  7500.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22800 entries, 0 to 22799
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   seller_type    22800 non-null  object
 1   bedroom        22800 non-null  int64
 2   layout_type    22800 non-null  object
 3   property_type  22800 non-null  object
 4   locality       22800 non-null  object
 5   price          22800 non-null  object
 6   area           22800 non-null  int64
 7   furnish_type   22800 non-null  object
 8   bathroom       22629 non-null  object
dtypes: int64(2), object(7)
memory usage: 1.6+ MB

In [7]:
df.isnull().sum()

seller_type        0
bedroom            0
layout_type        0
property_type      0
locality           0
price              0
area               0
furnish_type       0
bathroom         171
dtype: int64

In [9]:

# Use the actual column name from this dataset
# Available columns: seller_type, bedroom, layout_type, property_type, locality, price, area, furnish_type, bathroom

# Count entries by layout type

df.groupby('layout_type')['layout_type'].count()

layout_type
BHK    21726
RK      1074
Name: layout_type, dtype: int64

In [10]:
df.groupby('availability')['availability'].agg('count')

KeyError: 'availability'